### ISSUE TITLE
Using TLS1.3

### ISSUE THREAD

**Issue by valerauko** [aleph-io/aleph#434]
I'm having trouble communicating with sites that use TLS1.3: I get a handshake_failure.

It can be reliably reproduced with `https://mastodon.host` .

Tried:
* `clojure:openjdk-11-lein` `clojure:lein-alpine`
* JDK options `-Djdk.tls.client.protocols=TLSv1.3,TLSv1.2,TLSv1.1` and `-Dhttps.protocols=TLSv1.3,TLSv1.2,TLSv1.1,TLSv1`
* custom SSL context, failed both with only TLSv1.2 and only TLSv1.3 specified too

```clojure
(let [context (-> (SslContextBuilder/forClient)
                  (.protocols (into-array ["TLSv1.2"]))
                  .build)
      pool (http/connection-pool {:connection-options
                                   {:ssl-context context}})]
  @(manifold.deferred/chain
     (http/get "https://mastodon.host"
               {:pool pool})
     :body
     byte-streams/to-string))
```

Am I doing something wrong or is TLS1.3 just not supported yet?

I can see it [happening in the SSL test](https://www.ssllabs.com/ssltest/analyze.html?d=mastodon.host&s=163.172.7.58&latest) too, that's why I tried from the Java end, but no luck.

**Comment by kachayev** [comment]
@valerauko I don't think the issue has something to do with TLS1.3, with your JDK options the same exception occurs when using TLS1.2 too (using `-Djavax.net.debug=all` to get debug info about the connection):

```
javax.net.ssl|DEBUG|1D|aleph-netty-client-event-pool-1|2018-12-08 21:44:32.791 EET|SSLEngineOutputRecord.java:507|WRITE: TLS12 handshake, length = 245
...
javax.net.ssl|DEBUG|1D|aleph-netty-client-event-pool-1|2018-12-08 21:44:32.858 EET|SSLEngineInputRecord.java:214|READ: TLSv1.2 alert, length = 2
javax.net.ssl|DEBUG|1D|aleph-netty-client-event-pool-1|2018-12-08 21:44:32.859 EET|Alert.java:232|Received alert message (
"Alert": {
  "level"      : "fatal",
  "description": "handshake_failure"
}
)
```

**Comment by kachayev** [comment]
Forcing connection to use TLS1.3 work for me tho'. 

```clojure
(-> (SslContextBuilder/forClient)
    (.protocols (into-array ["TLSv1.3"]))
    .build)
```

from the code you've shared with JDK settings you've specified.

```shell
$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)
```

**Comment by valerauko** [comment]
No luck, on a clean Ubuntu Docker image with a freshly untared JDK
```
# java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```
With a project of nothing but a `project.clj`
```
(defproject testing "0.1.0"
  :description ""
  :url ""
  :main testing.core
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v20.html"}
  :jvm-opts ["-Djavax.net.debug=all"
             "-Djdk.tls.client.protocols=TLSv1.3,TLSv1.2"
             "-Dhttps.protocols=TLSv1.3,TLSv1.2"]
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [aleph "0.4.6"]])
```
and a `src/testing/core.clj`
```
(ns testing.core
  (:require [aleph.http :as http]
            [byte-streams :as bs]
            [manifold.deferred :as md])
  (:import [io.netty.handler.ssl SslContextBuilder]))

(defn -main []
  (let [context (-> (SslContextBuilder/forClient)
                    (.protocols (into-array ["TLSv1.3"]))
                    .build)
        pool (http/connection-pool {:connection-options
                                     {:ssl-context context}})]
    @(md/chain
       (http/get "https://mastodon.host" {:pool pool})
       :body
       bs/to-string)))
```
I'm still getting the "connection closed after" error. But with the debug option you suggested, I think I can see the real culprit:
```
javax.net.ssl|DEBUG|11|aleph-netty-client-event-pool-1-1|2018-12-09 02:36:01.797 GMT|HandshakeContext.java:290|Ignore unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 for TLS13
javax.net.ssl|DEBUG|11|aleph-netty-client-event-pool-1-1|2018-12-09 02:36:01.797 GMT|HandshakeContext.java:290|Ignore unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 for TLS13
javax.net.ssl|DEBUG|11|aleph-netty-client-event-pool-1-1|2018-12-09 02:36:01.798 GMT|HandshakeContext.java:290|Ignore unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 for TLS13
javax.net.ssl|DEBUG|11|aleph-netty-client-event-pool-1-1|2018-12-09 02:36:01.799 GMT|HandshakeContext.java:290|Ignore unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA for TLS13
javax.net.ssl|DEBUG|11|aleph-netty-client-event-pool-1-1|2018-12-09 02:36:01.806 GMT|HandshakeContext.java:290|Ignore unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA for TLS13
javax.net.ssl|DEBUG|11|aleph-netty-client-event-pool-1-1|2018-12-09 02:36:01.807 GMT|HandshakeContext.java:290|Ignore unsupported cipher suite: TLS_RSA_WITH_AES_128_GCM_SHA256 for TLS13
javax.net.ssl|DEBUG|11|aleph-netty-client-event-pool-1-1|2018-12-09 02:36:01.807 GMT|HandshakeContext.java:290|Ignore unsupported cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA for TLS13
javax.net.ssl|DEBUG|11|aleph-netty-client-event-pool-1-1|2018-12-09 02:36:01.808 GMT|HandshakeContext.java:290|Ignore unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA for TLS13
javax.net.ssl|DEBUG|11|aleph-netty-client-event-pool-1-1|2018-12-09 02:36:01.810 GMT|HandshakeContext.java:297|No available cipher suite for TLS13
javax.net.ssl|ERROR|11|aleph-netty-client-event-pool-1-1|2018-12-09 02:36:01.812 GMT|TransportContext.java:313|Fatal (HANDSHAKE_FAILURE): Couldn't kickstart handshaking (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
  	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:163)
  	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:95)
  	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:217)
  	at java.base/sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:103)
  	at io.netty.handler.ssl.SslHandler.handshake(SslHandler.java:1731)
  	at io.netty.handler.ssl.SslHandler.startHandshakeProcessing(SslHandler.java:1644)
  	at io.netty.handler.ssl.SslHandler.channelActive(SslHandler.java:1785)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941)
  	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
  	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:635)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.base/java.lang.Thread.run(Thread.java:834)}
)
```

**Comment by shilder** [comment]
You need to use at least netty [4.1.31.Final](https://netty.io/news/2018/10/30/4-1-31-Final.html) to be able to use TLS1.3. You can override netty version used by aleph by including these dependencies in your project.clj

```
[io.netty/netty-transport "4.1.32.Final"]
[io.netty/netty-transport-native-epoll "4.1.32.Final"]
[io.netty/netty-codec "4.1.32.Final"]
[io.netty/netty-codec-http "4.1.32.Final"]
[io.netty/netty-handler "4.1.32.Final"]
[io.netty/netty-handler-proxy "4.1.32.Final"]
[io.netty/netty-resolver "4.1.32.Final"]
[io.netty/netty-resolver-dns "4.1.32.Final"]
```

**Comment by valerauko** [comment]
I'm having the same issue after upgrading Netty to 4.1.32 Final

**Comment by kachayev** [comment]
@valerauko 

```Fatal (HANDSHAKE_FAILURE): Couldn't kickstart handshaking```

is a different error, let me try to reproduce this one.

**Comment by kachayev** [comment]
JDK 11+

```
root@18b1b8806d11:/var/aleph# java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Debian-3bpo91)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Debian-3bpo91, mixed mode, sharing)
```

OpenSSL 1.1.1+, build and linked manually

```
root@18b1b8806d11:/var/aleph# openssl version -a
OpenSSL 1.1.1a  20 Nov 2018
built on: Sat Feb  9 23:20:10 2019 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/ssl/lib/engines-1.1"
Seeding source: os-specific
```

JVM options:

* `-Djdk.tls.client.protocols=TLSv1.3`
* `-Dhttps.protocols=TLSv1.3`

Code:

```clojure
user=> (def context (-> (SslContextBuilder/forClient) (.protocols (into-array ["TLSv1.3"])) .build))
#'user/context
user=> (def pool (http/connection-pool {:connection-options {:ssl-context context}}))
#'user/pool
user=> @(http/get "https://mastodon.host" {:pool pool})
{:request-time 179, :aleph/keep-alive? true, :headers {"x-ua-compatible" "IE=Edge",...
```

**Comment by valerauko** [comment]
@kachayev I followed the instructions in your comment and can confirm it works.

Can we expect an Aleph release depending on a newer Netty (one supporting TLS1.3)?

**Comment by kachayev** [comment]
Latest tag is setup to use `4.1.36` (next one will use `4.1.51`).
